### ISSUE TITLE
IV.LATE (and IV.MSC and IV.NL9) metadata problem (channel missing coordinate info)

### ISSUE THREAD

**Issue by megies** [INGV/EIDA-metadata#1]
Original report by @shaharkadmiel in obspy/obspy#1839.

---

For some reason which I have not figured out yet, station IV.LATE (INGV, Latera) caused the ``read_inventory`` function to fail with an ``AttributeError: 'NoneType' object has no attribute 'strip'`` 

Traceback:

```python
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/core/inventory/inventory.py", line 72, in read_inventory
    format=format)[0]
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/core/util/base.py", line 462, in _read_from_plugin
    list_obj = read_format(filename, **kwargs)
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/io/stationxml/core.py", line 155, in _read_stationxml
    networks.append(_read_network(network, _ns))
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/io/stationxml/core.py", line 201, in _read_network
    stations.append(_read_station(station, _ns))
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/io/stationxml/core.py", line 242, in _read_station
    channels.append(_read_channel(channel, _ns))
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/io/stationxml/core.py", line 312, in _read_channel
    longitude=longitude, elevation=elevation, depth=depth)
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/core/inventory/channel.py", line 129, in __init__
    self.location_code = location_code
  File "/Users/shahar/anaconda2/lib/python2.7/site-packages/obspy/core/inventory/channel.py", line 207, in location_code
    self._location_code = value.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

After some debugging, I realised that in the ``_read_channel`` function, all values (longitude, latitude, elevation, depth, code, and location_code) are ``None`` and that causes the ``Channel.__init__`` to fail.

Currently, my workaround is to wrap line 237 in ``obspy/io/stationxml/core.py`` in a ``try/except`` statement:

```python
    channels = []
    for channel in sta_element.findall(_ns("Channel")):
        try:
            channels.append(_read_channel(channel, _ns))
        except AttributeError:
            warnings.warn('No channels available for station:\n'
                          '{}'.format(str(station)))
        # channels.append(_read_channel(channel, _ns))
    station.channels = channels
```

This results in a station entry in the inventory object with 0 channels.

I don't know if this is the preferred behavior but for now it works for me.

**Comment by shaharkadmiel** [comment]
This issue repeats for:

```
Station MSC (M. MASSICO)
	Station Code: MSC
	Channel Count: 0/2 (Selected/Total)
	2003-03-01T00:00:00.000000Z -
	Access: open
	Latitude: 41.19, Longitude: 13.97, Elevation: 109.0 m
	Available Channels:
```

and

```
Station NL9 (NOLA)
	Station Code: NL9
	Channel Count: 0/2 (Selected/Total)
	2003-03-01T00:00:00.000000Z -
	Access: open
	Latitude: 40.92, Longitude: 14.54, Elevation: 75.0 m
	Available Channels:
```

**Comment by petrrr** [comment]
The problems with stations `MSC` and `NL9` are already know, the provided metadata are insufficient. We are currently waiting that they get completed.

**Comment by petrrr** [comment]
The situation with `LATE`, however must be a different, because it did not emerge from systematic checks. I'll look into the issue with `LATE` ASAP (Unfortunately I am about to leave and will not be in office for some time). 

In general, I propose to report in different issue. Now for `MSC`, `NL9` just leave it as is, as we already aware of the details.

**Comment by petrrr** [comment]
Okay, the situation now seems to be a bit confusion. That is why I would propose to not mix different reports. The situation might look same or similar, but usually it is not.

I understand that the problem occurs when a station does not provide any channel entries (zero selected channels) in the Station XML. We are aware that the discrepancy between total and selected channel-epochs in the specific case is an anomaly. We are mostly aware of why this occurs.

However, the fact that there are no selected channel-epochs in a inventory should not be an problem and therefore should not create issues for the client.

Now for LATE, I see that the situation has already changed. There are still issues with some epochs but the described problem should not occur anymore. @shaharkadmiel: can you confirm?

**Comment by petrrr** [comment]
We have adjusted the service in a way that all channel-epochs are passed on, even if there are some missing information in the catalog. Still, the resulting stationXML is standard compliant. If optional information is missing it should be up to the client/application to handle this. 

If this still creates problems, feel free to open a new issue. We hope to improve the catalog entries ASAP, the specific issue should be solved now. So I am closing this one as "solved".
